### ISSUE TITLE
Alterar CNAME para docs.franzininho.com.br

### ISSUE THREAD

**Issue by RodrigoDornelles** [Franzininho/docs-franzininho-site#24]
Podemos alterar o endereço de <https://franzininho.github.io/docs-franzininho-site/docs> para <https://docs.franzininho.com.br> de maneira simples e gratuita no github pages.

Basta criar um arquivo chamado `CNAME` contendo o próprio site, e apontar o subdominio como CNAME pelo DNS

### Exemplo ###

| Github | Cloudflare |
| :-----: | :----------: |
![Screen Shot 2021-11-06 at 22 38 02](https://user-images.githubusercontent.com/29123479/140628974-e49b61af-2129-4318-a6fb-3cdecebbde99.png) | ![Screen Shot 2021-11-06 at 22 40 26](https://user-images.githubusercontent.com/29123479/140629030-6572ce37-4675-4286-b5a0-6721d95558e0.png)

**Comment by FBSeletronica** [comment]
Valeu @RodrigoDornelles

Tive que mudar a url base na configuração do docusaurus e colocaquei a url criada no registrobr nas configurações do ghpages. 

Deu certo.

Obrigado pela dica!
